config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get  "/signup",  to: "users#new"
  post "/signup",  to: "users#create"

  resources :users do
    member do
      get :following, :followers
    end
  end

  namespace :admin do
    root "users#index"
    resources :users
    resources :categories do
      resources :words
    end
    resources :words
  end

  resources :categories, only: [:index] do
    resources :lessons, expect: [:destroy]
  end
  resources :words
  resources :relationships, only: [:create, :destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @activities = Activity.user_activities(current_user).recent
        .paginate page: params[:page]
    end
  end
end

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="stats">
       <td><%= gravatar_for current_user %></td>
        <td><%= link_to current_user.name, current_user %></td>
        <%= render "shared/stats" %>
      </section>
      <section>
        <label class="button-inline">
          <%= button_to t("words_list"), words_path, :class => "btn btn-lg btn-primary", method: :get %>
        </label>
        <label class="button-inline">
          <%= button_to t("lesson"), categories_path, :class => "btn btn-lg btn-danger", method: :get %>
        </label>
      </section>
    </aside>
    <div class="col-md-8">
      <h3><%= t "activity" %></h3>
      <div class="panel-body">
        <%= render @activities %>
      </div>
      <div class="panel-footer text-center">
        <%= will_paginate @activities %>
      </div>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1><%= t "welcome" %></h1>
    <%= link_to t("sign-up-now"), signup_path, class: "btn btn-lg btn-primary" %>
  </div>
<% end %>