config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get  "/signup",  to: "users#new"
  post "/signup",  to: "users#create"

  resources :users do
    member do
      get :following, :followers
    end
  end

  namespace :admin do
    root "users#index"
    resources :users
    resources :categories do
      resources :words
    end
    resources :words
  end

  resources :categories, only: [:index] do
    resources :lessons, expect: [:destroy]
  end
  resources :words
  resources :relationships, only: [:create, :destroy]
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :category, optional: true
  has_many :results, dependent: :destroy
  has_many :meanings, dependent: :destroy, inverse_of: :word
  has_many :lessons, through: :results

  accepts_nested_attributes_for :meanings

  validates :content, presence: true, length: {maximum: Settings.user.word.maximum}
  accepts_nested_attributes_for :results

  scope :of_category, ->category_id do
    where category_id: category_id if category_id.present?
  end
  scope :learned, ->current_user_id do
    where "id IN (SELECT word_id FROM results WHERE lesson_id IN
      (SELECT id FROM lessons WHERE user_id = ?))", current_user_id
  end
  scope :not_learned, ->current_user_id do
    where "id NOT IN (SELECT word_id FROM results WHERE lesson_id IN
      (SELECT id FROM lessons WHERE user_id = ?))", current_user_id
  end
  scope :get_all, ->current_user_id{}
  scope :random, ->{order("RANDOM()").limit(Settings.word.quantity).map(&:id)}

  validate :check_meaning_nil

  private
  def check_meaning_nil
    correct_meaning =
      meanings.select{|meanings|meanings.is_correct? && !meanings.marked_for_destruction?}
    errors.add :correct_meaning,
      I18n.t("error.meaning_nil") if correct_meaning.empty?
  end
end

app/controllers/admin/words_controller.rb
class Admin::WordsController < ApplicationController
  before_action :logged_in_user
  before_action :verify_admin
  before_action :load_word, only: [:edit, :update, :destroy]
  before_action :load_categories

  def index
    @category = Category.find_by id: params[:category_id]
    if params[:category_id]
      @words = @category.words.paginate page: params[:page],
        per_page: Settings.user.per_page
    else
      @words = Word.paginate page: params[:page],
        per_page: Settings.user.per_page
    end
  end

  def new
    @word = Word.new
  end

  def show
  end

  def create
    @category = Category.find_by id: params[:category_id]
    @word = Word.new word_params
    if @word.save
      flash[:success] = t "created_success"
      redirect_to admin_words_path
    else
      flash[:danger] = t "created_not_success"
      render :new
    end
  end

  def edit
  end

  def update
    if @word.update_attributes word_params
      flash[:success] = t "updated_word"
      redirect_to admin_words_path
    else
      flash[:danger] = t "not_updated_word"
      render :edit
    end
  end

  def destroy
    if @word.destroy
      flash[:success] = t "deleted_word"
    else
      flash[:danger] = t "deleted_word_fail"
    end
    redirect_to admin_words_path
  end

  private
  def load_word
    @word = Word.find_by id: params[:id]
    unless @word
      flash[:danger] = t "load_word_fail"
      redirect_to admin_words_path
    end
  end

  def word_params
    params.require(:word).permit :content,
      :category_id, meanings_attributes: [:id, :content, :is_correct]
  end

  def load_categories
    @categories = Category.all
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :logged_in_user

  def index
    @categories = Category.all
    if params[:filter_state]
      @words = Word.of_category(params[:category_id]).send(params[:filter_state],
        current_user.id).paginate page: params[:page]
    else
      @words = Word.of_category(params[:category_id])
        .paginate page: params[:page]
    end
  end
end

app/views/admin/words/_meaning_field.html.erb
<div class="child">
  <div>
    <%= f.text_field :content %>
  </div>
  <div>
    <%= f.check_box :is_correct %>
    <%= f.label :is_correct, "is_correct" %>
  </div>
</div>

app/views/admin/words/_word.html.erb
<tr>
  <td><%= word.id %></td>
  <td><%= word.content %></td>
  <td><%= word.category.name %></td>
  <td>
    <%= link_to t("edit"),edit_admin_word_path(word),
      class: "btn btn-primary"%>
    <%= link_to t("delete"), admin_word_path(word), method: :delete,
      data: {confirm: t("are_you_sure")}, class: "btn btn-danger" %>
  </td>
</tr>

app/views/admin/words/edit.html.erb
<% provide :title, t("edit_word") %>
<h2><%= t "edit_word" %></h2>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @word] do |f| %>
      <%= render "shared/error_messages", object: f.object %>
      <%= f.collection_select :category_id, @categories, :id, :name %>
        <%= f.label :content %>
        <%= f.text_field :content, class: "form-control" %>
        <%= f.label :meanings %>
        <%= f.fields_for :meanings do |builder| %>
          <td><%= builder.text_field :content, class: "form-control" %></td>
          <%= f.label :is_correct %>
          <%= builder.check_box :is_correct, class: "check_but" %><br>
      <% end %>
      <%= f.submit t("edit"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admin/words/index.html.erb
<% provide :title, t("all_words") %>
<div class="container">
  <h1><%= t "all_words" %></h1>
  <div class="row text-left" style="padding-bottom: 20px">
    <%= link_to t("create"), new_admin_word_path,
      class: "btn btn-lg btn-primary" %>
  </div>
  <%= will_paginate %>
    <div class="">
      <table class="table table-hover">
        <thead>
          <tr>
            <th><%= t "id" %></th>
            <th><%= t "words" %></th>
            <th><%= t "category_name"%></th>
            <th><%= t "action" %></th>
          </tr>
        </thead>
        <tbody>
          <%= render @words %>
        </tbody>
      </table>
    </div>
  <%= will_paginate %>
</div>

app/views/admin/words/new.html.erb
<% provide :title, t("word_creation") %>
<h1><%= t "create_new_word" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @word] do |f| %>
    <%= render "shared/error_messages", object: f.object %>
      <%= f.collection_select :category_id, @categories, :id,:name %>
        <%= f.label :content %>
        <%= f.text_field :content, class: "form-control" %>
        <%= f.label :meanings %>
        <div id ="area_child">
        <%= f.fields_for :meanings do |builder| %>
          <div class="child">
            <td><%= builder.text_field :content, class: "form-control" %></td>
            <%= f.label :is_correct %>
            <%= builder.check_box :is_correct, class: "check_but" %><br>
          </div>
        <% end %>
        </div>
        <%= link_to t("add_more"), "javascript:void(0)", class: "add_mean" %>
      <%= f.submit t("create"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
<%= javascript_include_tag "words", "data-turbolinks-track": true %>